services:
  redpanda:
    image: redpandadata/redpanda:v25.3.9
    container_name: workshop-redpanda-1
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '1'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr
      - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - PLAINTEXT://redpanda:28082,OUTSIDE://localhost:8082
      - --rpc-addr
      - 0.0.0.0:33145
      - --advertise-rpc-addr
      - redpanda:33145
    ports:
      - 8082:8082
      - 9092:9092
      - 28082:28082
      - 29092:29092

  postgres:
    image: postgres:16
    container_name: workshop-postgres-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jobmanager:
    build:
      context: .
      dockerfile: flink/Dockerfile
    image: workshop-flink-py:1.20
    container_name: workshop-jobmanager-1
    command: jobmanager
    depends_on:
      - redpanda
      - postgres
    ports:
      - 8081:8081
    volumes:
      - ./workshop/src/job:/opt/src/job
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: workshop-flink-py:1.20
    container_name: workshop-taskmanager-1
    command: taskmanager
    depends_on:
      - jobmanager
    volumes:
      - ./workshop/src/job:/opt/src/job
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2

volumes:
  postgres_data:


