version: 2

sources:
  - name: raw_data
    description: "Raw data sources for NYC taxi rides"
    database: taxi_rides_ny
    schema: prod
    
    tables:
      - name: green_tripdata           
        description: "Raw green taxi trip data"
      - name: yellow_tripdata          
        description: "Raw yellow taxi trip data"
